name: Terraform Versioning and Changelog

on:
  workflow_run:
    workflows: ["Deploy Infrastructure"]
    types:
      - completed

permissions:
  id-token: write 
  contents: write   

jobs:
  version_and_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: ChangelogSession

      - name: Download Terraform State File from S3
        run: |
          aws s3 cp s3://pradeep-terraform-1234333/playback_improved/terraform.tfstate ./terraform.tfstate --region ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Show Terraform State Changes
        id: state_changes
        run: |
          terraform show -json terraform.tfstate > state_output.json
          jq -r '.values.root_module.resources[] | "Resource:

      - name: Just to see terraform state output in json format
        run: cat state_output.json

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "${{ secrets.USERNAME }}"
          git config user.email "${{ secrets.EMAIL }}"
          git add VERSION CHANGELOG.md
          git commit -m "Version bump to ${{ env.new_version }} with changelog"
          git push
